services:
  - type: web
    name: nfl-betting
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      # Install full app dependencies so server-side updates can run models
      pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    healthCheckPath: /health
    # Optional: configure a health check in the Render UI to GET /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "1"
      - key: DISABLE_ON_REQUEST_PREDICTIONS
        value: "1"
      - key: DISABLE_JSON_ODDS
        value: "1"
      # Admin endpoints: set a strong key to allow triggering daily updates from UI
      - key: ADMIN_KEY
        sync: false
      # Optional: token for pushing commits back to GitHub (Render supports repo connection; otherwise provide token)
      - key: GITHUB_TOKEN
        sync: false
      # Optional: Author identity for commit metadata
      - key: GIT_AUTHOR_NAME
        value: "Render Bot"
      - key: GIT_AUTHOR_EMAIL
        value: "render-bot@example.com"

cronJobs:
  - name: daily-admin-refresh
    # UTC schedule — adjust as needed (here: 10:00 UTC daily)
    schedule: "0 10 * * *"
    envVars:
      - key: ADMIN_KEY
        # Set this secret in Render dashboard or via 'render.yaml' sync
        sync: false
    command: |
      # Hit the admin endpoint to refresh odds, weather, predictions, and props
      curl -fsSL "https://nfl-betting.onrender.com/api/admin/daily-update?push=1&key=${ADMIN_KEY}" || true
