services:
  - type: web
    name: nfl-betting
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      # Install full app dependencies so server-side updates can run models
      pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    healthCheckPath: /health
    # Optional: configure a health check in the Render UI to GET /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "1"
      - key: DISABLE_ON_REQUEST_PREDICTIONS
        value: "1"
      - key: DISABLE_JSON_ODDS
        value: "1"
      # Prefer light daily updater + cap BLAS threads to avoid OOM on small plans
      - key: LIGHT_DAILY_UPDATE
        value: "1"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: NUMEXPR_MAX_THREADS
        value: "1"
      # Admin endpoints: set a strong key to allow triggering daily updates from UI
      - key: ADMIN_KEY
        sync: false
      # Optional: token for pushing commits back to GitHub (Render supports repo connection; otherwise provide token)
      - key: GITHUB_TOKEN
        sync: false
      # Optional: Author identity for commit metadata
      - key: GIT_AUTHOR_NAME
        value: "Render Bot"
      - key: GIT_AUTHOR_EMAIL
        value: "render-bot@example.com"

cronJobs:
  - name: daily-admin-refresh
    # UTC schedule — adjust as needed (here: 10:00 UTC daily)
    schedule: "0 10 * * *"
    envVars:
      - key: ADMIN_KEY
        # Set this secret in Render dashboard or via 'render.yaml' sync
        sync: false
    command: |
      # Hit the admin endpoint to refresh odds, weather, predictions, and props (light mode by default)
      curl -fsSL "https://nfl-betting.onrender.com/api/admin/daily-update?push=1&light=1&key=${ADMIN_KEY}" || true
  - name: odds-refresh-30min
    # Refresh odds frequently so EV/edges/recommendations reflect latest markets
    schedule: "*/30 * * * *"  # every 30 minutes
    envVars:
      - key: ADMIN_KEY
        sync: false
    command: |
      curl -fsSL "https://nfl-betting.onrender.com/api/admin/daily-update?push=0&light=1&key=${ADMIN_KEY}" || true
  - name: weekly-totals-calibration
    # Run every Tuesday at 09:00 UTC (after MNF completes) to fit last 4 completed weeks
    schedule: "0 9 * * 2"
    envVars:
      - key: ADMIN_KEY
        sync: false
    command: |
      curl -fsSL "https://nfl-betting.onrender.com/api/admin/calibration/fit?weeks=4&push=1&key=${ADMIN_KEY}" || true
